name: release
on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 23.1.2
          elixir-version: 1.11.3
      - name: Build Elixir Releases
        run: |
          cd agma && mix deps.get && env MIX_ENV=prod mix release && cd ..
          cd pig && mix deps.get && env MIX_ENV=prod mix release && cd ..
          cd shoujo && mix deps.get && env MIX_ENV=prod mix release && cd ..
          cd wand && mix deps.get && env MIX_ENV=prod mix escript.build && cd ..
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            agma/_build/prod/rel/agma/bin/agma
            pig/_build/prod/rel/pig/bin/pig
            shoujo/_build/prod/rel/shoujo/bin/shoujo
            wand/wand
